[
"Aarey Road",
"Agashi",
"Agripada",
"Alibag",
"Altamount Road",
"Ambernath",
"Ambernath East",
"Ambernath West",
"Ambivali",
"Amboli",
"Andheri East",
"Andheri West",
"Andheri-Kurla Road",
"Antop Hill",
"Anushakti Nagar",
"Asangaon ",
"Atgaon",
"Azad Nagar",
"Badlapur East",
"Badlapur West",
"Bandra East",
"Bandra Kurla Complex",
"Bandra West",
"Bangur Nagar",
"barve Nagar",
"Behram Baug",
"Best Nagar",
"Beverly Park",
"Bhadane",
"Bhandup East",
"Bhandup West",
"Bhayandar East",
"Bhayandar West",
"Bhivpuri",
"Bhiwandi",
"Bhuleshwar",
"Boisar",
"Boraj",
"Borivali East",
"Borivali West",
"Borla",
"Breach Candy",
"Byculla East",
"Byculla West",
"C.P. Tank",
"Carter Road",
"Chakala",
"Chandivali",
"Charkop",
"Charni Road",
"Chedda Nagar",
"Chembur",
"chembur Colony",
"Chikuwadi",
"Chinchpada",
"Chinchpokli",
"Chiplun",
"Chira Bazar",
"chirag Nagar",
"Chuna Bhatti",
"Church Gate",
"Colaba",
"Cuffe Parade",
"Cumballa Hill",
"Currey Road",
"Dadar East",
"Dadar West",
"Dahanu",
"Dahanu Road",
"Dahisar East",
"Dahisar West",
"Deonar",
"Dhamote",
"Dharavi",
"Dindoshi",
"Dohole",      
"Dombivli East",
"Dombivli West",
"Dongri",
"Elphinstone Road",
"Evershine Nagar",
"Fort",
"G T B Nagar",
"Gaibi Nagar",
"Gamdevi",
"Gandhi Nagar",
"Ghatkopar East",
"Ghatkopar West",
"Ghatla",
"Ghera Sudhagad",
"Ghodbunder",
"Girgaon",
"Gokuldam",
"Gokuldham Colony",
"Golibar",
"Gorai",
"Goregaon East",
"Goregaon West",
"Govandi",
"Govind Nagar",
"Grant Road East",
"Grant Road West",
"Gulmohar Road",
"Haji Ali",
"Harihareshwar",
"IC Colony",
"J B Nagar",
"Jacob Circle",
"Jai Ambe Nagar",
"Jawhar",
"Jogeshwari East",
"Jogeshwari West",
"Juhu",
"Juhu Tara Road",
"Kajupada",
"Kalbadevi",
"Kalher",
"Kalina",
"Kalyan East",
"Kalyan West",
"Kalyan-Shil Road",
"Kamatghar",
"Kanakia Road",
"Kandivali East",
"Kandivali West",
"Kanjurmarg",
"Kanjurmarg East",
"Kanjurmarg West",
"Kannamwar Nagar ",
"Kanti Park",
"Karjat",
"Kasara",
"Kashimira",
"Kemps Corner",
"Khadakpada",
"Khan Abdul Gafar Road",
"Khandale",
"Khandas Road",
"Khar East",
"Khar West",
"Khardi",
"Kharodi",
"Khetwadi",
"Khodala",
"Khopoli",
"kidwai Nagar",
"Kolad",
"Kurla East",
"Kurla West",
"Lal Baug",
"LBS Marg",
"LBS Marg-Mulund",     
"Link Road",
"Linking Road",
"Lokhandwala",
"Lonere",
"Lower Parel",
"Madh",
"Magathane",
"Mahad",
"Mahalaxmi",
"Mahavir Nagar",
"Mahim",
"Malabar Hill",
"Malabar Hill",
"Malad East",
"Malad West",
"Malvani",
"Mandapeshwar",
"Mandvi",
"Mankhurd",
"Manor",
"Manori",
"Marine Lines",
"Marol",
"Masjid Bunder",
"Matunga East",
"Matunga West",
"Mazgaon",
"MHADA Colony",
"Mhatwali",
"Mira Bhayandar",
"Mira Road",
"Mulund Colony",
"Mulund East",
"Mulund West",
"Mumbai - Nasik Highway",
"Mumbai Central",
"Murbad",
"Murbad Karjat Road",
"Murbad Road",
"Murud",
"Nagaon",
"Nagothane",
"Nagpada",
"Nahur East",
"Nahur West",
"Naigaon East",
"Naigaon West",
"Nalasopara East",
"Nalasopara West",
"Narayan Patil Wadi",
"Nariman Point",
"Navapada",
"Navghar Road",
"Naya Nagar",
"Nehru Nagar",
"Nehru Road",
"Neral",
"Netaji Nagar",
"Opera House",
"Orlem Malad",
"Oshiwara",
"Palghar",
"Pali",
"Pali Hill",
"Panth Nagar",
"Parel",
"Peddar Road",
"Poonam Nagar",
"postal Colony",
"Powai",
"Prabhadevi",
"Prabhu Ali",
"Pydhonie",
"Raigad",
"Ramnagar",
"Roha",      
"Royal Palms",
"S V Road",
"Sahakar Nagar",
"Sahar",
"Sakawar",
"Sakinaka",
"Samat Nagar",
"Santacruz East",
"Santacruz West",
"Saralgoan",
"Saravali",
"Sarvodaya Nagar",
"Senapati Bapat Marg",
"Sewri",
"sewri West",
"Shahad",
"Shahapur",
"Shastri Nagar",
"Shivaji Nagar",
"Shivaji Park",
"Sindhi Society",
"Sion East",
"Sion West",
"Sir JJ Road",
"Talasari",
"Tardeo",
"Thakurdwar",
"Thakurli",
"Tilak Nagar",
"Titwala",
"Triveni Nagar",
"Trombay",
"Tulsiwadi",
"Ulhasnagar",
"Umerkhadi",
"Umroli",
"Upper Parel",
"Upper Worli",
"Uttan",
"V P ROAD",
"Vakola",
"Vangani",
"Vasai East",
"Vasai Road",
"Vasai West",
"Vasai-Nallasopara Link Road",
"Vasind",
"Veera Desai Road",
"Vehloli",
"Versova",
"Vidya Nagari",
"Vidyavihar",
"vidyavihar East",
"vidyavihar West",
"Vijay Nagar",
"Vikhroli East",
"Vikhroli West",
"Vikramgad",
"Vile Parle East",
"Vile Parle West",
"Vindhane",
"Virar East",
"Virar West",
"Vitthalwadi",
"Wada",
"Wadala East",
"Wadala West",
"Walkeshwar",
"Warden Road",
"Western Express Highway",
"Worli",
"Yari Road",
"Yogi Jawraj Nagar",
"Zadghar"
]     